name: formatting

on: pull_request

jobs:
  run-linters:
    name: Run formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: pip install black
      - name: Run linters / formatters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          auto_fix: true
