name: tests

on: [push]

jobs:
  wget:
    name: test-nc
    runs-on: ubuntu-latest
    steps:
      - name: install Python
        uses: actions/setup-python@v4
      - name: install pkgs
        run: |
          pip install hdf5 netCDF4 xarray pytest pydap
      - name: bare curl
        run: |
          curl \
            -O https://icdc.cen.uni-hamburg.de/thredds/dodsC/ftpthredds/hamtide//m2.hamtide11a.nc \
            -o /tmp/by_curl.nc
      - name: pytest
        run: |
          pytest tests test_github_action.py

