name: tests

on: [push]

jobs:
  mytest:
    name: test-nc
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
      - name: install pkgs
        run: |
          pip install "netCDF4<1.6" xarray pytest pydap
      - name: bare curl
        run: |
          curl \
            -O https://icdc.cen.uni-hamburg.de/thredds/dodsC/ftpthredds/hamtide//m2.hamtide11a.nc \
            -o /tmp/by_curl.nc
          pwd
          ls
      - name: pytest
        run: |
          pytest tests/test_github_action.py

